### PR TITLE
Use new notification format so we can set a priority.

### PR DESCRIPTION
**Pull request by gwynantj**
## Description
- The current version was using an old format to send a push notification.
- This PR is basically an existing PR here (but with tests): https://github.com/tompesman/push-apns/pull/8
- The documentation for the binary format is covered here: https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Appendixes/BinaryProviderAPI.html#//apple_ref/doc/uid/TP40008194-CH106-SW5
- Added tests to verify that the binary format is correct
- It's had an internal code review [here](https://github.com/Fatsoma/push-apns/pull/1) but feel free to add more comments

### CODE REVIEW

**Comment by gwynantj** [comment]
@tompesman due to no response from the original pull request author I think we should close that PR in favour of this one?

**Comment by tompesman** [comment]
@gwynantj nice work! Merging! Should I release a 1.1 version or a 2.0 version?

**Comment by gwynantj** [comment]
@tompesman it's not a breaking change so I would go for a 1.1 version. 👍

**Comment by tompesman** [comment]
version 1.1.0 is released to rubygems

**Pull request merged**
